version: "3.9"

services:
  web02:
    image: nginx:latest
    container_name: webserver_app_2
    restart: unless-stopped
    tty: true
    ports:
      - "1080:80"
    labels:
      - "traefik.enable=true" # enables the service
      - "traefik.http.routers.web02.rule=Host(`web02.prosethsolutions.com`)" # domain to expose on
      - "traefik.http.routers.web02.entrypoints=web" # if you named your 443 entrypoint differently than webscure, substitute it here!
        #- "traefik.http.routers.webserver.tls=true" # if you named your cert resolver differently than letsencrypt, substitute it here!
      - "traefik.http.services.web02.loadbalancer.server.port=80"
    volumes:
      - ./src:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
    links:
      - php
    networks:
      - traefik-global-proxy
      - laravel_app_networks_2

  php:
    image: chanmesa/php-laravel:latest
    container_name: php_app_2
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: php
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./src:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel_app_networks_2

  db:
    image: mysql:latest
    container_name: db_app_2
    restart: unless-stopped
    tty: true
    ports:
      - "5306:3306"
    environment:
      MYSQL_DATABASE: db_docker
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      SERVICE_NAME: mysql
      SERVICE_TAGS: dev
    volumes:
      - db:/var/lib/mysql
      - ./mysql/my.conf:/etc/mysql/my.conf
    networks:
      - laravel_app_networks_2

  web02phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:latest
    container_name: phpmyadmin_app_2
    restart: unless-stopped
    ports:
      - "8090:80"
    labels:
      - "traefik.enable=true" # enables the service
      - "traefik.http.routers.web02phpmyadmin.rule=Host(`web02phpmyadmin.prosethsolutions.com`)" # domain to expose on
      - "traefik.http.routers.web02phpmyadmin.entrypoints=web" # if you named your 443 entrypoint differently than webscure, substitute it here!
        #- "traefik.http.routers.webserver.tls=true" # if you named your cert resolver differently than letsencrypt, substitute it here!
      - "traefik.http.services.web02phpmyadmin.loadbalancer.server.port=80"
     
    environment:
      PMA_HOST: db
    networks:
      - traefik-global-proxy      
      - laravel_app_networks_2

networks:
  laravel_app_networks_2:
    driver: bridge
  traefik-global-proxy:
    external: true

volumes:
  db:
    driver: local
